### ISSUE TITLE
请问目标检测的帧率有多少呢？

### ISSUE THREAD

**Issue by DaMiBear** [yxhuang7538/rknn_yolov5_3588_hyx#2]
看tb搭载RK3588的rock5只要999也想入一块，还请问大佬项目运行的帧率有多少呢？我本来是打算用NCNN试一试的，今天突然发现大佬的仓库。

**Comment by yxhuang7538** [comment]
刚看到，目前只有69帧左右

**Comment by DaMiBear** [comment]
69帧感觉已经很高了呀😮。淘宝ROCK5B要Q3才能发货，准备先拿RK3568试一试小的yolo-fastest网络。
